name: CD
on:
  pull_request:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p dist
          zip -r dist/build.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: pacote
          path: dist/build.zip
  release:
    if: startsWith(github.ref,'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pacote
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/build.zip
